namespace Start.API
{
    /// <summary>
    ///     Defines the various types of elements in the Start system.
    /// </summary>
    public enum StartElementTypeEnum
    {
        ALL = -1,
        PIPE_ELEMENT = 0,
        NODE = 1,
        RIGID_ELEMENT = 2,
        CYLINDRICAL_SHELL = 3,
        FLEXIBLE_ELEMENT = 5,
        CONE_ELEMENT = 6,
        PIPE_BEND = 10,
        MILTER_BEND = 11,
        FABRICATED_TEE = 13,
        WELDED_TEE = 14,
        VALVE = 15,
        ANGULAR_EXPANSION_JOINT = 16,
        AXIAL_EXPANSION_JOINT = 17,
        LATERAL_EXPANSION_JOINT = 18,
        STUB_IN = 19,
        ANCHOR = 20,
        SLIDING_SUPPORT = 21,
        GUIDE_SINGLE_DIRECTION_SUPPORT = 22,
        RIGID_HANGER = 23,
        SPRING_HANGER = 24,
        SPRING_SUPPORT = 25,
        HINGED_ANCHOR = 26,
        CONSTANT_FORCE_SUPPORT = 27,
        MARKER = 28,
        GUIDE_DOUBLE_DIRECTION_SUPPORT = 29,
        COLD_SPRING_PRE_STRETCH = 30,
        PRE_COMPRESSION = 31,
        LINEAR_RESTRAINT_MOVEMENT = 32,
        ANGULAR_RESTRAINT_MOVEMENT = 33,
        RELATIVE_LINEAR_DISPLACEMENT_IN_THE_NODE = 34,
        RELATIVE_ROTATIONAL_DISPLACEMENT_IN_THE_NODE = 35,
        NONSTANDARD_EXPANSION_JOINT = 40,
        NONSTANDARD_RESTRAINT = 41,
        NONSTANDARD_TEE = 42,
        LONG_RADIUS_PIPE_BEND = 43,
        PRE_STRESSED_PIPE_BEND = 44,
        WELDED_BEND = 45,
        ELBOW = 46,
        CAP = 47,
        MILTER_JOINT = 48,
        FLANGE = 49,
        ELASTIC_RESTRAINT = 51,
        ONE_WAY_RESTRAINT = 52,
        TWO_WAY_RESTRAINT = 53,
        TEMPERATURE_CYCLE = 60,
        BASE_CLASS_OF_TEMPERATURES_CYCLES = 61,
        REDUCER_CONCENTRIC = 63,
        REDUCER_ECCENTRIC = 64,
        CONSTANT_FORCE_SUPPORT_HANGER = 66,
        CONNECTOR = 68,
        AXIAL_EXPANSION_SLIP_JOINT = 70,
        NONSTANDARD_BEND = 71,
        WELDOLET = 72,
        SWEEPOLET = 73,
        EXTRUDED_TEE = 74,
        UNIVERSAL_EXPANSION_JOINT = 76,
        TORSION_EXPANSION_JOINT = 77,
        VESSEL = 79,
        TANK = 80,
        PUMP_API_610 = 81,
        TURBINE = 82,
        COMPRESSOR = 83,
        AIR_COOLER = 84,
        FRIED_HEATER = 85,
        PUMP_ISO_9905 = 86,
        PUMP_ISO_5199 = 87,
        INLINE_PUMP = 88,
        OTHER_PUMP = 89,
        DAMPER = 92,
        BALL_EXPANSION_JOINT = 94,
        STAND_TEE = 95,
        SADDLE_BEND = 96,
        SINGLE_FLANGE = 98,
        SUPPORT_LOAD = 101,
        NODE_DISPLACEMENT = 102,
        EXPANSION_JOINT_DEFORMATION = 103,
        SPRING_HANGER_PROPERTIES = 104,
        CODE_STRESS = 110
    }
}