//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFCConverter.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFCConverter.Localization.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory does not exist.
        /// </summary>
        internal static string DirectoryDoesNotExists_Error {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportWindowForm_ExportButton_Text {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown export type.
        /// </summary>
        internal static string ExportWindowForm_ExportType_Error {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export type.
        /// </summary>
        internal static string ExportWindowForm_ExportType_Label_Text {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportType_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        internal static string ExportWindowForm_ExportType_Topological {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportType_Topological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex.
        /// </summary>
        internal static string ExportWindowForm_ExportType_Vertex {
            get {
                return ResourceManager.GetString("ExportWindowForm_ExportType_Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to .ifc file cannot be empty.
        /// </summary>
        internal static string ExportWindowForm_OutputFilePath_Empty_Error {
            get {
                return ResourceManager.GetString("ExportWindowForm_OutputFilePath_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a full path of IFC file to be saved.
        /// </summary>
        internal static string ExportWindowForm_OutputFilePath_Label_Text {
            get {
                return ResourceManager.GetString("ExportWindowForm_OutputFilePath_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to be saved.
        /// </summary>
        internal static string ExportWindowForm_SaveDialogFile_Title {
            get {
                return ResourceManager.GetString("ExportWindowForm_SaveDialogFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string ExportWindowForm_selectOutputFilePathButton_Text {
            get {
                return ResourceManager.GetString("ExportWindowForm_selectOutputFilePathButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to IFC.
        /// </summary>
        internal static string ExportWindowForm_Text {
            get {
                return ResourceManager.GetString("ExportWindowForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex segments.
        /// </summary>
        internal static string ExportWindowForm_VertexSegments_Textbox {
            get {
                return ResourceManager.GetString("ExportWindowForm_VertexSegments_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex segments num shoud be above 4.
        /// </summary>
        internal static string ExportWindowForm_VertexSegmentsNum_Error {
            get {
                return ResourceManager.GetString("ExportWindowForm_VertexSegmentsNum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportWindowForm_ImportButton_Text {
            get {
                return ResourceManager.GetString("ImportWindowForm_ImportButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVEVA.
        /// </summary>
        internal static string ImportWindowForm_ImportType_Aveva {
            get {
                return ResourceManager.GetString("ImportWindowForm_ImportType_Aveva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown import type.
        /// </summary>
        internal static string ImportWindowForm_ImportType_Error {
            get {
                return ResourceManager.GetString("ImportWindowForm_ImportType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import profile.
        /// </summary>
        internal static string ImportWindowForm_ImportType_Label_Text {
            get {
                return ResourceManager.GetString("ImportWindowForm_ImportType_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to .ifc file cannot be empty.
        /// </summary>
        internal static string ImportWindowForm_InputFilePath_Empty_Error {
            get {
                return ResourceManager.GetString("ImportWindowForm_InputFilePath_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a full path of IFC file to be imported.
        /// </summary>
        internal static string ImportWindowForm_InputFilePath_Label_Text {
            get {
                return ResourceManager.GetString("ImportWindowForm_InputFilePath_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string ImportWindowForm_selectInputFilePathButton_Text {
            get {
                return ResourceManager.GetString("ImportWindowForm_selectInputFilePathButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from IFC.
        /// </summary>
        internal static string ImportWindowForm_Text {
            get {
                return ResourceManager.GetString("ImportWindowForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Title_Error {
            get {
                return ResourceManager.GetString("MessageBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permissions to write to this directory.
        /// </summary>
        internal static string UnauthorizedAccess_Error {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_Error", resourceCulture);
            }
        }
    }
}
